<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Tentang Kami</name>
   <tag></tag>
   <elementGuidId>54968927-e3f0-43de-9b81-c443fba25f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/section/div/div/a[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1926448d-aa37-4222-9c10-adc88eb71aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tentang Kami</value>
      <webElementGuid>688c3ee1-4c37-4ff6-9a15-9a2bac7757dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;footer__Container-sc-h97ats-0 jPXmDj&quot;]/section[1]/div[@class=&quot;menu&quot;]/div[@class=&quot;box&quot;]/a[@class=&quot;link&quot;]/p[1]</value>
      <webElementGuid>28c3a612-608a-4b86-9aeb-42c32b285c31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/section/div/div/a[2]/p</value>
      <webElementGuid>36370d04-9374-4951-8820-cfb287158f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/following::p[3]</value>
      <webElementGuid>819b258a-574f-42c0-b3b9-3d188a52f004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formula rahasia'])[1]/following::p[3]</value>
      <webElementGuid>b0b7b71f-8e5a-49d4-90a1-73fba25473b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/p</value>
      <webElementGuid>a99568f7-e93a-4eab-b7ae-2fa47f32d5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Tentang Kami' or . = 'Tentang Kami')]</value>
      <webElementGuid>9b57208d-68cb-4c23-ba78-60b58e2a461b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
