<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Redaksi Deduktif</name>
   <tag></tag>
   <elementGuidId>0ed1cd20-1271-4fdd-9590-5ac665b45e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>02f8d8b5-1554-437f-a2e6-3a823d97e2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Redaksi Deduktif</value>
      <webElementGuid>ee7731a4-4345-42d0-8691-f8d35a10acaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;redaksi__Container-sc-1xszji8-0 gHVfcm&quot;]/div[@class=&quot;container&quot;]/h1[1]</value>
      <webElementGuid>eb93222b-6229-45f9-9174-7c808c81f2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/h1</value>
      <webElementGuid>187aa50c-e3f4-4778-9b66-4e6dde503638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redaksi'])[2]/following::h1[1]</value>
      <webElementGuid>0892e452-13de-43b9-8770-2ae26b3559ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Kami'])[2]/following::h1[1]</value>
      <webElementGuid>4d9813ca-6bf2-4d7b-9908-db8fa314604b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemimpin Redaksi'])[1]/preceding::h1[1]</value>
      <webElementGuid>ed4d6150-0951-43d4-b281-ecaa30df13fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dewan Redaksi'])[1]/preceding::h1[1]</value>
      <webElementGuid>8df76907-1c08-4fc6-bedd-b89f71a50462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>27349d93-5cfe-4fcb-aa09-cc41542ed3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Redaksi Deduktif' or . = 'Redaksi Deduktif')]</value>
      <webElementGuid>94e094b6-1bc4-4b3d-8d6f-1759d742d293</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
