<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fajar Nugraha_imgthumb</name>
   <tag></tag>
   <elementGuidId>7905d4e2-cd3e-4da9-b882-8199ad54d3b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='article']/div/div/nav/div/div/a[2]/div/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>49c58f24-be70-4ba1-88e4-8ecfa3fc9737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hidup di Antara Pertaruhan</value>
      <webElementGuid>84c29d2a-28f3-48d9-8bce-b73b72385a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hidup di Antara Pertaruhan</value>
      <webElementGuid>a7182952-d6d6-4954-8780-f5168252fcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>05d4e672-baf1-4ea1-a507-5851ecf0fe96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=640&amp;q=75 640w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=750&amp;q=75 750w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=828&amp;q=75 828w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>1997546c-3e7f-437b-9de8-be280cb27512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=3840&amp;q=75</value>
      <webElementGuid>d8dc2d52-8b82-4b73-a692-8cf9cda1e548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>fdc6819d-a2fa-4b91-be7e-65aff2a2e806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>041ae1a4-92e8-41ac-8270-bfeb0d0a675b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgthumb</value>
      <webElementGuid>44a01dc0-0c1e-47e8-9706-56ea7a91ed27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article&quot;)/div[@class=&quot;footnews&quot;]/div[@class=&quot;footnews__Container-sc-72vph7-0 kQWfYl&quot;]/nav[@class=&quot;footer&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;slider-container&quot;]/a[@class=&quot;newspart&quot;]/div[@class=&quot;news&quot;]/div[@class=&quot;images&quot;]/div[@class=&quot;imgrel&quot;]/span[1]/img[@class=&quot;imgthumb&quot;]</value>
      <webElementGuid>e17d3b23-4f27-4781-842c-7f63bc49e556</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='article']/div/div/nav/div/div/a[2]/div/div/div/span/img</value>
      <webElementGuid>6395a730-a0ae-44ae-85f4-724dd9cb9e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hidup di Antara Pertaruhan']</value>
      <webElementGuid>21e31392-7d84-4df5-93a7-220ad53babe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div/div/span/img</value>
      <webElementGuid>b9a2bf63-164f-4097-88bb-ff2c32825e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Hidup di Antara Pertaruhan' and @alt = 'Hidup di Antara Pertaruhan' and @src = '/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1662587135_ilustrasi-Rumah-Judi-2-landscape-Deduktif-Rangga-Putrawicaksana.png&amp;w=3840&amp;q=75']</value>
      <webElementGuid>6ad9430a-8e8d-42a6-b972-91423f78d43a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
