<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7d049e87-804c-42f0-87dc-e06dc6bdc749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/article/div/a/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Rumah di Persimpangan Jalan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dd7ed04b-77b5-4af5-bb30-110ae9196eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rumah di Persimpangan Jalan</value>
      <webElementGuid>c47ecbad-bbfe-45df-9242-2c63344300bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=3840&amp;q=75</value>
      <webElementGuid>3aabe173-920d-4aaf-b44e-5f889706447c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>484ad582-8044-415f-8c45-384b7c29c72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>9351dae3-c2e2-4c56-a277-951fda4dabd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>6cf99cf6-e8fc-4e1b-b1ed-1540737ba0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=640&amp;q=75 640w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=750&amp;q=75 750w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=828&amp;q=75 828w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>b01ae1f7-b7a6-406f-b23e-14f20b696b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;listdata__Container-sc-i584bf-0 eepZwG deduktif&quot;]/article[1]/div[1]/a[@class=&quot;indeks-link&quot;]/div[@class=&quot;article&quot;]/div[@class=&quot;left&quot;]/span[1]/img[1]</value>
      <webElementGuid>006d4bac-4ada-47f2-9f6f-4aec056ba7d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/article/div/a/div/div/span/img</value>
      <webElementGuid>8a366ab2-7ed2-442a-95d4-0a4a240f7810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rumah di Persimpangan Jalan']</value>
      <webElementGuid>c37cf050-7104-4286-a6b5-1f3f39187991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>3ac53068-d8c3-4918-b1a2-83c6cec815a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Rumah di Persimpangan Jalan' and @src = '/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1665045391_ilustrasi-Rumah-di-Persimpangan-Jalan-landscape_medium_deduktif_rangga_putrawicaksana.png&amp;w=3840&amp;q=75']</value>
      <webElementGuid>15f60e36-877f-41ec-9e9d-9e9f2d71dd8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
