<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rumah di Persimpangan Jalan</name>
   <tag></tag>
   <elementGuidId>33d8d78a-2bf7-48be-9101-f7c87d33e5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/article/div/a/div/div[2]/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.article-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9cc89980-2913-44f1-a738-84626a3825b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>article-title</value>
      <webElementGuid>c49f7761-3ab3-4ab4-90f9-c81f4bfb76dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rumah di Persimpangan Jalan</value>
      <webElementGuid>f772d5f6-f8fa-4d7e-98aa-f5b078cf31c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;listdata__Container-sc-i584bf-0 eepZwG deduktif&quot;]/article[1]/div[1]/a[@class=&quot;indeks-link&quot;]/div[@class=&quot;article&quot;]/div[@class=&quot;credit&quot;]/p[@class=&quot;article-title&quot;]</value>
      <webElementGuid>a46e0411-8670-4c61-8412-da40a0238f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/article/div/a/div/div[2]/p[2]</value>
      <webElementGuid>c57e81a5-d755-469b-94de-03757daa70e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEDUKTIF'])[1]/following::p[2]</value>
      <webElementGuid>d45c614a-350b-4fc5-89af-6034dd029de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RSS'])[1]/following::p[2]</value>
      <webElementGuid>78d0ae41-ee01-421e-bb6e-fd4c051798cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rumah di Persimpangan Jalan']/parent::*</value>
      <webElementGuid>b87249ae-cf0f-4e80-8e02-e7a4eb23180c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>6e36528f-ab64-492d-a2a5-ff39b2ce9444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rumah di Persimpangan Jalan' or . = 'Rumah di Persimpangan Jalan')]</value>
      <webElementGuid>e072ca4f-79ec-49a8-aa65-5cee56b6baf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
