<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Charlene Kayla_imgthumb</name>
   <tag></tag>
   <elementGuidId>423ddd20-c951-46d3-a932-6a7266f1bfda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='article']/div/div/nav/div/div/a/div/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.imgthumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc4e3346-97e6-4ba4-abaa-5a835663bcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Martin Aleida dan Riwayat Harian Rakjat</value>
      <webElementGuid>6b558d4a-6a48-4e3e-9197-1dbea2e06f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Martin Aleida dan Riwayat Harian Rakjat</value>
      <webElementGuid>a5842acd-daa9-4bde-bf1e-84263d1c5570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>670475c6-aa0f-4ecc-83dd-88ab5c6c378f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=640&amp;q=75 640w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=750&amp;q=75 750w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=828&amp;q=75 828w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>6cee83d4-d00f-449f-8a25-58a8da8f1619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=3840&amp;q=75</value>
      <webElementGuid>9ea3f472-f5a5-453b-89b1-9bfec1d8ec10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b86eeb73-fea6-45d4-8e5f-cb7871f3bb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>8e22646d-77cc-4870-80d7-0d466cf4656d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgthumb</value>
      <webElementGuid>29c22254-c3fe-431d-a34b-18782a7f7709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article&quot;)/div[@class=&quot;footnews&quot;]/div[@class=&quot;footnews__Container-sc-72vph7-0 kQWfYl&quot;]/nav[@class=&quot;footer&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;slider-container&quot;]/a[@class=&quot;newspart&quot;]/div[@class=&quot;news&quot;]/div[@class=&quot;images&quot;]/div[@class=&quot;imgrel&quot;]/span[1]/img[@class=&quot;imgthumb&quot;]</value>
      <webElementGuid>616792c1-36bc-457f-b3ef-0fe812865c79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='article']/div/div/nav/div/div/a/div/div/div/span/img</value>
      <webElementGuid>0255d1ac-3336-4878-8a5b-f65fc26f3b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Martin Aleida dan Riwayat Harian Rakjat']</value>
      <webElementGuid>d7005d35-3cd2-4e9e-9c08-43015e1a25b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span/img</value>
      <webElementGuid>08e512e2-ff7f-42bc-a2fa-846e23008031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Martin Aleida dan Riwayat Harian Rakjat' and @alt = 'Martin Aleida dan Riwayat Harian Rakjat' and @src = '/_next/image?url=https%3A%2F%2Ffiles.jurno.id%2Fuploads%2Fimages%2Fdeduktif%2F1664519686_ilustrasi_landscape_Aset-PKI-deduktif_rangga_putrawicaksana.png&amp;w=3840&amp;q=75']</value>
      <webElementGuid>33ccf427-6f7c-4998-ace4-c378eaed9904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
