<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Redaksi_deduktif</name>
   <tag></tag>
   <elementGuidId>bc4ab374-bf36-4572-9c9f-9b5274c6f805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/nav/div/div/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.deduktif</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4da42c9-8214-4a15-808e-1007817131e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Deduktif Website</value>
      <webElementGuid>dcc29a75-c9e8-4f97-ad7f-877511d3f556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/deduktif.svg</value>
      <webElementGuid>b0580186-23be-4d49-a309-14d236cf6726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>1d3ec243-1bda-4a71-b803-95d166a2c221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>1ad6720f-e37a-4b5c-b53c-caf852f0f490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deduktif</value>
      <webElementGuid>73090002-d8d6-4a83-9953-facdcbb140fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>ca1322f7-948b-46a3-bd77-e7c1f3c89f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/deduktif.svg 640w, /images/deduktif.svg 750w, /images/deduktif.svg 828w, /images/deduktif.svg 1080w, /images/deduktif.svg 1200w, /images/deduktif.svg 1920w, /images/deduktif.svg 2048w, /images/deduktif.svg 3840w</value>
      <webElementGuid>ed225b8a-22bc-4212-9e21-c1d4e8c56f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;header__Container-sc-14n1q57-0 fJWfAy&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;topbar__Container-sc-11aj7yt-0 GnmNv&quot;]/nav[1]/div[@class=&quot;topbar&quot;]/div[@class=&quot;header-logo false&quot;]/a[@class=&quot;link&quot;]/span[1]/img[@class=&quot;deduktif&quot;]</value>
      <webElementGuid>7d0e94e7-0d18-4367-a512-e6344ba25614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/nav/div/div/a/span/img</value>
      <webElementGuid>b18f24c6-c160-4ac0-88f8-8287df99991a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Deduktif Website']</value>
      <webElementGuid>fdc917fd-89a8-44c9-9ca0-a18070b15282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9fd1b8e0-119c-421c-a7ff-45b817609143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Deduktif Website' and @src = '/images/deduktif.svg']</value>
      <webElementGuid>75c711c2-06f5-41ba-acee-c057a6146e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
