<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Redaksi_deduktif</name>
   <tag></tag>
   <elementGuidId>6f999912-d74b-49fd-aa75-6149266630ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/nav/div/div/div/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.deduktif</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a42deeb2-8302-4ae5-8271-6185062e60b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Deduktif Website</value>
      <webElementGuid>ecf45295-6318-4495-968f-e58e3c6c9cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>9678ee56-60fe-4b90-9fee-17d030e7f8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/deduktif.svg 640w, /images/deduktif.svg 750w, /images/deduktif.svg 828w, /images/deduktif.svg 1080w, /images/deduktif.svg 1200w, /images/deduktif.svg 1920w, /images/deduktif.svg 2048w, /images/deduktif.svg 3840w</value>
      <webElementGuid>48469f9e-6bf2-4a72-91aa-98b0aa53da1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/deduktif.svg</value>
      <webElementGuid>98a338c4-161f-493f-8d92-9ad1e41ada13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>42d4f2c4-bb13-4ea5-859e-5d12c7442b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>8248ccda-0f45-4ed2-ab66-b794d9030948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deduktif</value>
      <webElementGuid>62413d65-6f60-4030-897d-3bca74895c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;header__Container-sc-14n1q57-0 fJWfAy&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;topbar__Container-sc-11aj7yt-0 GnmNv&quot;]/nav[1]/div[@class=&quot;topbar&quot;]/div[@class=&quot;header-logo deduktif&quot;]/div[@class=&quot;deduktif-logo&quot;]/a[@class=&quot;link deduktif&quot;]/span[1]/img[@class=&quot;deduktif&quot;]</value>
      <webElementGuid>bdb8f09d-856b-4c5f-aa33-af9e88d634de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/nav/div/div/div/a/span/img</value>
      <webElementGuid>01c215cc-631e-409d-bd7c-c10413792cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Deduktif Website']</value>
      <webElementGuid>c0e7b987-5d39-4997-984f-e15b4da8cc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ac59feb2-0082-4c7a-8f82-d7d53e388b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Deduktif Website' and @src = '/images/deduktif.svg']</value>
      <webElementGuid>1fc33b14-c30c-49db-8659-0ebec4317b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
